[package]
name = "wbe"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.20"
eframe = "0.21.0"
egui = "0.21.0"
eyre = "0.6.8"
nom = "7.1.3"
regex = "1.7.1"
rustls-connector = "0.16.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
unicode-segmentation = "1.10.1"
